name: Rust
on:
  push:
    branches:
      - trunk
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt
    - run: git diff-index --quiet HEAD -- || (git diff && exit 1)
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test
